CREATE TABLE IF NOT EXISTS USER_TBL
(
  USER_ID VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  LEVEL_OF_EXPERTISE INTEGER NOT NULL,
  SPEED INTEGER NOT NULL,
  PRIMARY KEY(USER_ID)
);

CREATE TABLE IF NOT EXISTS USER_LOGS
(
  ID INTEGER NOT NULL,
  SPEED INTEGER NOT NULL,
  NO_OF_WALL_COLLISIONS INTEGER NOT NULL,
  TASK_NUMBER INTEGER NOT NULL,
  USER_ID VARCHAR(255) NOT NULL,
  IS_SUCCESS VARCHAR(255) NOT NULL,
  TIME_TAKEN INTEGER NOT NULL,
  TIMESTAMP DATE NOT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY(USER_ID) REFERENCES USER_TBL(USER_ID)
);